/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardIndexImport } from './routes/dashboard_/index'
import { Route as DashboardCardIdImport } from './routes/dashboard_/$cardId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/dashboard_/',
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardCardIdRoute = DashboardCardIdImport.update({
  id: '/dashboard_/$cardId',
  path: '/dashboard/$cardId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard_/$cardId': {
      id: '/dashboard_/$cardId'
      path: '/dashboard/$cardId'
      fullPath: '/dashboard/$cardId'
      preLoaderRoute: typeof DashboardCardIdImport
      parentRoute: typeof rootRoute
    }
    '/dashboard_/': {
      id: '/dashboard_/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard/$cardId': typeof DashboardCardIdRoute
  '/dashboard': typeof DashboardIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/$cardId': typeof DashboardCardIdRoute
  '/dashboard': typeof DashboardIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard_/$cardId': typeof DashboardCardIdRoute
  '/dashboard_/': typeof DashboardIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard/$cardId' | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard/$cardId' | '/dashboard'
  id: '__root__' | '/' | '/dashboard_/$cardId' | '/dashboard_/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardCardIdRoute: typeof DashboardCardIdRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardCardIdRoute: DashboardCardIdRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard_/$cardId",
        "/dashboard_/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard_/$cardId": {
      "filePath": "dashboard_/$cardId.tsx"
    },
    "/dashboard_/": {
      "filePath": "dashboard_/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
